format_version: 10
pipelines:
  master-ami:
    group: terraform
    materials:
      git-801da91:
        git: https://github.com/donthi123/master-ami.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: "AES:cf4GO2ogEtUnQLATHte1gA==:jVlTpDikDsgyFdXLm1whYRyriwctZRqg34oTe8e/Cgw="
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: terraform, arguments: [ "init" ], run_if: passed}
                - exec: {command: terraform, arguments: [ "apply", "-auto-approve"], run_if: passed}
